/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    // Seed avatars and company logos are generated by DiceBear rather than
    // stored locally - this clone deliberately has no object storage.
    remotePatterns: [{ protocol: 'https', hostname: 'api.dicebear.com' }],
  },
};

export default nextConfig;
